Repository rainlab/user-plugin, pull requests merged in 2019-07, with the labels that each got.

#312 Implement remember login mode choice
  components/Account.php
  components/account/signin.htm
  lang/en/lang.php
  models/Settings.php
  models/settings/fields.yaml
Labels: Status: Completed, Type: Enhancement

#393 Update lang.php
  lang/nl/lang.php
Labels: Status: Completed, Type: Maintenance

#394 Update lang (ru) in settings
  lang/ru/lang.php
Labels: Status: Completed, Type: Maintenance

#303 Added requirement for user to enter his old password when changing important settings.
  components/Account.php
  components/account/update.htm
  lang/en/lang.php
  models/Settings.php
  models/settings/fields.yaml
Labels: Type: Enhancement
